import type { Metadata } from 'next';
import { Lexend, Zilla_Slab } from 'next/font/google';
import './globals.css';
import Navbar from '@/_components/ui/navbar';

const lexend = Lexend({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-lexend',
  display: 'swap',
});

const zillaSlab = Zilla_Slab({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-zilla-slab',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.variable} ${zillaSlab.variable} antialiased h-screen bg-fixed bg-linear-to-br from-green-light/20 to-mint-light/30`}
      >
        <Navbar />
        <div className="pt-20">{children}</div>
      </body>
    </html>
  );
}
